name: Sophia Script 🐛
description: Report errors or unexpected behavior 🤔
body:
- type: markdown
  attributes:
    value: >
      Make sure you are able to repro it on the latest released version. Please open a [new discussion](https://github.com/farag2/Sophia-Script-for-Windows/discussions/new) if you have an idea.
      If you prefer Telegram, you may visit out [chat](https://t.me/sophia_chat), or [Discord](https://discord.gg/sSryhaEv79). Languages allowed: English & русский.
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: Verify that this is not a Windows issue;
      required: true
    - label: Refer to the [system requirements](https://github.com/farag2/Sophia-Script-for-Windows#system-requirements);
      required: true
    - label: Refer to the [How to use](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use);
      required: true
    - label: I do not use a homebrew Windows image;
      required: true
    - label: I did not tweak Windows before that could cause system instability;
      required: false
    - label: If your issue concerns the Wrapper, please mention @BenchTweakGaming in issue
    - label: Upload you Sophia.ps1 preset file
- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder:  Write something :)
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: Write something :)
    placeholder: Describe the issue you are facing with
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshot with an error
    placeholder: Paste here a screenshot with an error
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ## Device information
- type: input
  attributes:
    label: Windows Version
    description: Which version of Windows are you using? Type `winver` in Start menu.
    placeholder: e.g. Windows 11 24H2 26100.2605
  validations:
    required: true
- type: input
  id: sophia-script-version
  attributes:
    label: Sophia Script version
    description: Which version of Sophia Script are you using?
    placeholder: e.g. 6.7.3
  validations:
    required: true
