name: Badge Lines

on:
  push:
    branches:
      - master
    # tags:
    # - '*.*.*'
  pull_request:
    branches:
      - master

jobs:
  update-badges:
    name: Update Badge Lines
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Get Sophia_Script_for_Windows_11 folder lines number
        run: |
          $Summary = 0
          Get-ChildItem -Path src\Sophia_Script_for_Windows_11 -File -Recurse | ForEach-Object -Process {
              $Summary += ((Get-Content -Path $_.FullName).Count | Measure-Object -Sum).Sum
          }
          $Summary = "{0:N1}k" -f ($Summary/1000)

          Write-Verbose -Message $Summary -Verbose

          echo "CODE_LINES=$Summary" >> $env:GITHUB_ENV

      - name: Writing to Gist
        uses: schneegans/dynamic-badges-action@master
        with:
          auth: ${{ secrets.GIST_SophiaScript }}
          gistID: 9852d6b9569a91bf69ceba8a94cc97f4
          filename: SophiaScript.json
          label: Lines of Code
          message: ${{ env.CODE_LINES }}
          namedLogo: PowerShell
          color: brightgreen
